const express=require("express");
const path=require("path");
const {Client}=require("@gradio/client");
const app=express(); app.use(express.json({limit:"1mb"})); app.use(express.static(path.join(__dirname,"public")));
const PORT=process.env.PORT||3000;
const clean=v=>String(v??"").trim();
function prompt(s){return `Create ONE professional fashion design board, not a person photo and not a collage. Show exactly one complete garment centered in full front view. Garment: ${clean(s.garment)}. Style: ${clean(s.style)}. Pattern: ${clean(s.pattern)}. Fit: ${clean(s.fit)}. Neckline: ${clean(s.neckline)}. Sleeves: ${clean(s.sleeves)}. Sleeve length: ${clean(s.sleeveLength)}. Garment length: ${clean(s.length)}. Waist: ${clean(s.waist)}. Lower cut: ${clean(s.leg)}. Fabric: ${clean(s.fabric)}. Color: ${clean(s.color)}. Details: ${clean(s.details)}. Use a clean light background. Add elegant callout lines around the SAME garment with small zoomed views of its neckline, sleeve, fabric and details. Do not add another garment, model, mannequin, shoes, bag or unrelated objects. Do not change the garment type or invent clothing parts. Make it look like a polished AI fashion infographic.`}
function fallback(s){let esc=x=>clean(x).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));let svg=`<svg xmlns="http://www.w3.org/2000/svg" width="900" height="1200"><rect width="100%" height="100%" fill="#f7f3ec"/><text x="450" y="70" text-anchor="middle" font-size="34" font-family="Arial">لوحة تصميم الأزياء</text><text x="450" y="115" text-anchor="middle" font-size="25" font-family="Arial">${esc(s.garment)}</text><path d="M300 280Q360 190 450 235Q540 190 600 280L570 700Q540 850 450 900Q360 850 330 700Z" fill="#9e4652" stroke="#222" stroke-width="6"/><path d="M360 245Q450 330 540 245M330 330L220 520M570 330L680 520" fill="none" stroke="#222" stroke-width="6"/><line x1="300" y1="450" x2="120" y2="360" stroke="#777" stroke-width="2"/><text x="55" y="345" font-size="23" font-family="Arial">القصّة</text><line x1="600" y1="500" x2="780" y2="410" stroke="#777" stroke-width="2"/><text x="700" y="395" font-size="23" font-family="Arial">الخامة</text><text x="450" y="1030" text-anchor="middle" font-size="23" font-family="Arial">اللون: ${esc(s.color)}</text><text x="450" y="1080" text-anchor="middle" font-size="21" font-family="Arial">التفاصيل: ${esc(s.details)}</text><text x="450" y="1145" text-anchor="middle" font-size="18" font-family="Arial">Norjan © 2026</text></svg>`;return"data:image/svg+xml;charset=utf-8,"+encodeURIComponent(svg)}
app.post("/api/generate",async(req,res)=>{let s=req.body||{};try{let c=await Promise.race([Client.connect(process.env.HF_SPACE||"Tongyi-MAI/Z-Image-Turbo"),new Promise((_,r)=>setTimeout(()=>r(new Error("timeout")),20000))]);let r;try{r=await c.predict("/generate",{prompt:prompt(s),resolution:"1024x1024",seed:Math.floor(Math.random()*2e9),steps:9,shift:3,enhance:true})}catch(e){r=await c.predict("/generate_image",{prompt:prompt(s),height:1024,width:1024,num_inference_steps:9,seed:Math.floor(Math.random()*2e9),randomize_seed:true})}let x=r?.data?.[0],image=typeof x==="string"?x:(x?.url||x?.path||x?.image);if(!image)throw Error("no image");res.json({image,ai:true})}catch(e){res.json({image:fallback(s),ai:false})}});
app.get("*",(req,res)=>res.sendFile(path.join(__dirname,"public","index.html")));app.listen(PORT);
